/******************************************************************
* supervisory_state_machine.hpp - Supervisory State Machine Boundary
* Author: Project 6 Team
* Last Modified: 2026-06-07
* @file supervisory_state_machine.hpp
* @brief Declares the narrow API around the ESE-generated state machine.
******************************************************************/

#pragma once

#include <cstdint>
#include <memory>
#include <optional>

#include "supervisory/can/can_protocol.hpp"
#include "supervisory/common/event.hpp"

namespace project6::supervisory
{

class cSupervisoryController;
struct sStateMachineContext;

/**
 * @brief Public high-level state names reported by the supervisory state machine.
 *
 * These values mirror the major ESE states while keeping generated state-machine
 * details out of the rest of the program.
 */
enum class ecSupervisoryControlState
{
    Idle,
    Dispatching,
    MovingUp,
    MovingDown,
    Arrived,
    Faulted
};

/**
 * @brief Snapshot of high-level control state for diagnostics and tests.
 *
 * This type is safe to expose to tests, simulator adapters, and status
 * endpoints. It intentionally avoids exposing generated ESE internals.
 */
struct sSupervisoryStateSnapshot
{
    /** Current public state, translated from the generated machine state. */
    ecSupervisoryControlState controlState = ecSupervisoryControlState::Idle;

    /** Most recently confirmed elevator floor. */
    std::uint8_t currentFloor = 1;

    /** Floor selected for the active request. */
    std::uint8_t targetFloor = 1;

    /** Commanded or reported travel direction. */
    ecTravelDirection direction = ecTravelDirection::None;

    /** Whether the supervisor currently considers the doors open. */
    bool isDoorOpen = false;

    /** Latched fault flag that drives the machine into Faulted. */
    bool isFaulted = false;
};

/**
 * @brief Public API for the ESE-backed supervisory state machine.
 *
 * The generated ESE machine stays in the corresponding C++ file.
 * Callers interact with this class by feeding normalized events and reading a
 * diagnostic snapshot.
 */
class cSupervisoryStateMachineAPI
{
public:
    cSupervisoryStateMachineAPI();

    /**
     * @brief Releases the state-machine context.
     */
    ~cSupervisoryStateMachineAPI();

    cSupervisoryStateMachineAPI(const cSupervisoryStateMachineAPI&) = delete;
    cSupervisoryStateMachineAPI& operator=(const cSupervisoryStateMachineAPI&) = delete;

    /**
     * @brief Applies one normalized event and advances the ESE machine once.
     *
     * Requests are queued, status reports update the snapshot, timer events
     * advance door and movement timers, and faults are latched before one state
     * machine update is evaluated.
     *
     * @param event Event produced by CAN, timer, or fault handling code.
     */
    void handleEvent(const sSupervisoryEvent& event);

    /**
     * @brief Returns the latest public state snapshot.
     *
     * @return Value copy suitable for diagnostics, tests, or status endpoints.
     */
    [[nodiscard]] sSupervisoryStateSnapshot snapshot() const;

    /**
     * @brief Removes the CAN frame generated by the latest control transition.
     *
     * @return The pending frame, or std::nullopt when no transmission is due.
     */
    [[nodiscard]] std::optional<sCanFrame> tryTakePendingCanFrame();

private:
    /** Translates the generated machine state into the public snapshot enum. */
    void refreshSnapshotState();

    /** Owns queued requests, timers, fault state, and the public snapshot. */
    std::unique_ptr<sStateMachineContext> smContext_;

    /** Owns the generated ESE state-machine implementation. */
    std::unique_ptr<cSupervisoryController> smMachine_;
};

} // namespace project6::supervisory
