# ese pre-processor project
# (C) 2026 ESE Project Contributors
# Author: Ryan Pratt

from .model import Action, Machine


def generate_cpp(machine: Machine) -> str:
    enter_actions = _actions_by_state(machine.actions, "enter")
    exit_actions = _actions_by_state(machine.actions, "exit")
    conditionals = {conditional.name: conditional.expression for conditional in machine.conditionals}
    lines: list[str] = [
        f"// #ESE-GENERATED-BEGIN: {machine.name}",
        "// Generated by esepp. Do not edit this section by hand.",
        "",
        f"class {machine.name}",
        "{",
        "public:",
        "    enum class State",
        "    {",
    ]
    for index, state in enumerate(machine.states):
        comma = "," if index < len(machine.states) - 1 else ""
        lines.append(f"        {state.name}{comma}")
    lines += [
        "    };",
        "",
        f"    {machine.name}()",
        "    {",
        f"        enter{_pascal(machine.initial)}();",
        "    }",
        "",
        "    void update()",
        "    {",
        "        switch (currentState)",
        "        {",
    ]
    for state in machine.states:
        pascal_state = _pascal(state.name)
        lines += [
            f"            case State::{state.name}:",
            "            {",
            f"                update{pascal_state}();",
            "                break;",
            "            }",
            "",
        ]
    lines += [
        "        }",
        "    }",
        "",
        "    State getState() const",
        "    {",
        "        return currentState;",
        "    }",
        "",
        "private:",
        f"    State currentState = State::{machine.initial};",
        "",
    ]

    for state in machine.states:
        lines += [f"    void update{_pascal(state.name)}()", "    {"]
        for transition in state.transitions:
            lines += [
                f"        if (condition{_pascal(transition.condition)}())",
                "        {",
                f"            transitionTo(State::{transition.target});",
                "            return;",
                "        }",
            ]
        lines += ["    }", ""]

    for conditional in machine.conditionals:
        lines += [
            f"    bool condition{_pascal(conditional.name)}()",
            "    {",
            f"        return {conditionals[conditional.name]};",
            "    }",
            "",
        ]

    lines += [
        "    void transitionTo(State nextState)",
        "    {",
        "        if (currentState == nextState)",
        "        {",
        "            return;",
        "        }",
        "",
        "        switch (currentState)",
        "        {",
    ]
    for state in machine.states:
        lines += [
            f"            case State::{state.name}:",
            "            {",
            f"                exit{_pascal(state.name)}();",
            "                break;",
            "            }",
            "",
        ]
    lines += [
        "        }",
        "",
        "        currentState = nextState;",
        "",
        "        switch (currentState)",
        "        {",
    ]
    for state in machine.states:
        lines += [
            f"            case State::{state.name}:",
            "            {",
            f"                enter{_pascal(state.name)}();",
            "                break;",
            "            }",
            "",
        ]
    lines += ["        }", "    }", ""]

    for state in machine.states:
        lines += _action_function("enter", state.name, enter_actions.get(state.name, ""))
        lines.append("")
    for state in machine.states:
        lines += _action_function("exit", state.name, exit_actions.get(state.name, ""))
        lines.append("")

    lines += ["};", "", f"// #ESE-GENERATED-END: {machine.name}"]
    return "\n".join(lines)


def _actions_by_state(actions: list[Action], kind: str) -> dict[str, str]:
    return {action.state: action.body for action in actions if action.kind == kind}


def _action_function(kind: str, state: str, body: str) -> list[str]:
    lines = [f"    void {kind}{_pascal(state)}()", "    {"]
    if body:
        lines.extend(_indent_raw_body(body, "        "))
    lines.append("    }")
    return lines


def _indent_raw_body(body: str, indent: str) -> list[str]:
    return [indent + line.rstrip() if line.strip() else "" for line in body.splitlines()]


def _pascal(name: str) -> str:
    parts = [part for part in name.replace("-", "_").split("_") if part]
    if len(parts) > 1:
        return "".join(part[:1].upper() + part[1:] for part in parts)
    return name[:1].upper() + name[1:]
