/*
Build and run on Windows with:
clang++ -std=c++23 -fuse-ld=lld elevator.cpp -o elevator_test.exe
*/

#include <cstdint>
#include <deque>
#include <print>

/* Test block comment
- This may break the parser in unexpected ways
*/

constexpr int kLowestFloor = 0;
constexpr int kHighestFloor = 2;

std::deque<int> physicalRequests;
std::deque<int> remoteRequests;
std::deque<int> carCommands;

int currentFloor = 0;
int targetFloor = 0;
int motorDirection = 0;
int secondsSinceArrival = 0;
bool doorOpen = false;

int clampFloor(int floor)
{
    if (floor < kLowestFloor)
    {
        return kLowestFloor;
    }
    if (floor > kHighestFloor)
    {
        return kHighestFloor;
    }
    return floor;
}

bool hasPhysicalRequest()
{
    return !physicalRequests.empty();
}

bool hasRemoteRequest()
{
    return !remoteRequests.empty();
}

bool hasCarCommand()
{
    return !carCommands.empty();
}

void acceptNextPhysicalRequest()
{
    targetFloor = clampFloor(physicalRequests.front());
    physicalRequests.pop_front();
}

void acceptNextRemoteRequest()
{
    targetFloor = clampFloor(remoteRequests.front());
    remoteRequests.pop_front();
}

void acceptNextCarCommand()
{
    targetFloor = clampFloor(carCommands.front());
    carCommands.pop_front();
}

void commandMotorUp()
{
    motorDirection = 1;
}

void commandMotorDown()
{
    motorDirection = -1;
}

void stopMotor()
{
    motorDirection = 0;
}

void openDoors()
{
    doorOpen = true;
}

void closeDoors()
{
    doorOpen = false;
}

void startArrivalWait()
{
    secondsSinceArrival = 0;
}

/* #ESE-BEGIN

machine ElevatorController {
    initial Idle;

    state Idle {
        on physicalRequestPending -> DispatchPhysical;
        on remoteRequestPending -> DispatchRemote;
    }

    state DispatchPhysical {
        on targetIsCurrentFloor -> Arrived;
        on targetAboveCurrentFloor -> MovingUp;
        on targetBelowCurrentFloor -> MovingDown;
    }

    state DispatchRemote {
        on targetIsCurrentFloor -> Arrived;
        on targetAboveCurrentFloor -> MovingUp;
        on targetBelowCurrentFloor -> MovingDown;
    }

    state Arrived {
        on carCommandReceived -> DispatchCarCommand;
        on arrivalWaitExpired -> Idle;
    }

    state DispatchCarCommand {
        on targetIsCurrentFloor -> Arrived;
        on targetAboveCurrentFloor -> MovingUp;
        on targetBelowCurrentFloor -> MovingDown;
    }

    state MovingUp {
        on reachedTargetFloor -> Arrived;
    }

    state MovingDown {
        on reachedTargetFloor -> Arrived;
    }
}

conditionals ElevatorController {
    physicalRequestPending = hasPhysicalRequest();
    remoteRequestPending = hasRemoteRequest();
    carCommandReceived = hasCarCommand();
    arrivalWaitExpired = secondsSinceArrival >= 10;
    targetIsCurrentFloor = targetFloor == currentFloor;
    targetAboveCurrentFloor = targetFloor > currentFloor;
    targetBelowCurrentFloor = targetFloor < currentFloor;
    reachedTargetFloor = currentFloor == targetFloor;
}

actions ElevatorController {
    enter DispatchPhysical {
        acceptNextPhysicalRequest();
    }

    enter DispatchRemote {
        acceptNextRemoteRequest();
    }

    enter DispatchCarCommand {
        acceptNextCarCommand();
    }

    enter MovingUp {
        closeDoors();
        commandMotorUp();
    }

    enter MovingDown {
        closeDoors();
        commandMotorDown();
    }

    exit MovingUp {
        stopMotor();
    }

    exit MovingDown {
        stopMotor();
    }

    enter Arrived {
        stopMotor();
        openDoors();
        startArrivalWait();
    }

    exit Arrived {
        closeDoors();
    }
}

#ESE-END */

// #ESE-GENERATED-BEGIN: ElevatorController
// Generated by esepp. Do not edit this section by hand.

class ElevatorController
{
public:
    enum class State
    {
        Idle,
        DispatchPhysical,
        DispatchRemote,
        Arrived,
        DispatchCarCommand,
        MovingUp,
        MovingDown
    };

    ElevatorController()
    {
        enterIdle();
    }

    void update()
    {
        switch (currentState)
        {
            case State::Idle:
            {
                updateIdle();
                break;
            }

            case State::DispatchPhysical:
            {
                updateDispatchPhysical();
                break;
            }

            case State::DispatchRemote:
            {
                updateDispatchRemote();
                break;
            }

            case State::Arrived:
            {
                updateArrived();
                break;
            }

            case State::DispatchCarCommand:
            {
                updateDispatchCarCommand();
                break;
            }

            case State::MovingUp:
            {
                updateMovingUp();
                break;
            }

            case State::MovingDown:
            {
                updateMovingDown();
                break;
            }

        }
    }

    State getState() const
    {
        return currentState;
    }

private:
    State currentState = State::Idle;

    void updateIdle()
    {
        if (conditionPhysicalRequestPending())
        {
            transitionTo(State::DispatchPhysical);
            return;
        }
        if (conditionRemoteRequestPending())
        {
            transitionTo(State::DispatchRemote);
            return;
        }
    }

    void updateDispatchPhysical()
    {
        if (conditionTargetIsCurrentFloor())
        {
            transitionTo(State::Arrived);
            return;
        }
        if (conditionTargetAboveCurrentFloor())
        {
            transitionTo(State::MovingUp);
            return;
        }
        if (conditionTargetBelowCurrentFloor())
        {
            transitionTo(State::MovingDown);
            return;
        }
    }

    void updateDispatchRemote()
    {
        if (conditionTargetIsCurrentFloor())
        {
            transitionTo(State::Arrived);
            return;
        }
        if (conditionTargetAboveCurrentFloor())
        {
            transitionTo(State::MovingUp);
            return;
        }
        if (conditionTargetBelowCurrentFloor())
        {
            transitionTo(State::MovingDown);
            return;
        }
    }

    void updateArrived()
    {
        if (conditionCarCommandReceived())
        {
            transitionTo(State::DispatchCarCommand);
            return;
        }
        if (conditionArrivalWaitExpired())
        {
            transitionTo(State::Idle);
            return;
        }
    }

    void updateDispatchCarCommand()
    {
        if (conditionTargetIsCurrentFloor())
        {
            transitionTo(State::Arrived);
            return;
        }
        if (conditionTargetAboveCurrentFloor())
        {
            transitionTo(State::MovingUp);
            return;
        }
        if (conditionTargetBelowCurrentFloor())
        {
            transitionTo(State::MovingDown);
            return;
        }
    }

    void updateMovingUp()
    {
        if (conditionReachedTargetFloor())
        {
            transitionTo(State::Arrived);
            return;
        }
    }

    void updateMovingDown()
    {
        if (conditionReachedTargetFloor())
        {
            transitionTo(State::Arrived);
            return;
        }
    }

    bool conditionPhysicalRequestPending()
    {
        return hasPhysicalRequest();
    }

    bool conditionRemoteRequestPending()
    {
        return hasRemoteRequest();
    }

    bool conditionCarCommandReceived()
    {
        return hasCarCommand();
    }

    bool conditionArrivalWaitExpired()
    {
        return secondsSinceArrival >= 10;
    }

    bool conditionTargetIsCurrentFloor()
    {
        return targetFloor == currentFloor;
    }

    bool conditionTargetAboveCurrentFloor()
    {
        return targetFloor > currentFloor;
    }

    bool conditionTargetBelowCurrentFloor()
    {
        return targetFloor < currentFloor;
    }

    bool conditionReachedTargetFloor()
    {
        return currentFloor == targetFloor;
    }

    void transitionTo(State nextState)
    {
        if (currentState == nextState)
        {
            return;
        }

        switch (currentState)
        {
            case State::Idle:
            {
                exitIdle();
                break;
            }

            case State::DispatchPhysical:
            {
                exitDispatchPhysical();
                break;
            }

            case State::DispatchRemote:
            {
                exitDispatchRemote();
                break;
            }

            case State::Arrived:
            {
                exitArrived();
                break;
            }

            case State::DispatchCarCommand:
            {
                exitDispatchCarCommand();
                break;
            }

            case State::MovingUp:
            {
                exitMovingUp();
                break;
            }

            case State::MovingDown:
            {
                exitMovingDown();
                break;
            }

        }

        currentState = nextState;

        switch (currentState)
        {
            case State::Idle:
            {
                enterIdle();
                break;
            }

            case State::DispatchPhysical:
            {
                enterDispatchPhysical();
                break;
            }

            case State::DispatchRemote:
            {
                enterDispatchRemote();
                break;
            }

            case State::Arrived:
            {
                enterArrived();
                break;
            }

            case State::DispatchCarCommand:
            {
                enterDispatchCarCommand();
                break;
            }

            case State::MovingUp:
            {
                enterMovingUp();
                break;
            }

            case State::MovingDown:
            {
                enterMovingDown();
                break;
            }

        }
    }

    void enterIdle()
    {
    }

    void enterDispatchPhysical()
    {
        acceptNextPhysicalRequest();
    }

    void enterDispatchRemote()
    {
        acceptNextRemoteRequest();
    }

    void enterArrived()
    {
        stopMotor();
                openDoors();
                startArrivalWait();
    }

    void enterDispatchCarCommand()
    {
        acceptNextCarCommand();
    }

    void enterMovingUp()
    {
        closeDoors();
                commandMotorUp();
    }

    void enterMovingDown()
    {
        closeDoors();
                commandMotorDown();
    }

    void exitIdle()
    {
    }

    void exitDispatchPhysical()
    {
    }

    void exitDispatchRemote()
    {
    }

    void exitArrived()
    {
        closeDoors();
    }

    void exitDispatchCarCommand()
    {
    }

    void exitMovingUp()
    {
        stopMotor();
    }

    void exitMovingDown()
    {
        stopMotor();
    }

};

// #ESE-GENERATED-END: ElevatorController

//========================================================
// General printing helpers
//========================================================
const char* stateName(ElevatorController::State state)
{
    switch (state)
    {
        case ElevatorController::State::Idle:
            return "Idle";
        case ElevatorController::State::DispatchPhysical:
            return "DispatchPhysical";
        case ElevatorController::State::DispatchRemote:
            return "DispatchRemote";
        case ElevatorController::State::Arrived:
            return "Arrived";
        case ElevatorController::State::DispatchCarCommand:
            return "DispatchCarCommand";
        case ElevatorController::State::MovingUp:
            return "MovingUp";
        case ElevatorController::State::MovingDown:
            return "MovingDown";
    }

    return "<unknown>";
}

const char* motorName()
{
    if (motorDirection > 0)
    {
        return "up";
    }
    if (motorDirection < 0)
    {
        return "down";
    }

    return "stopped";
}

const char* doorName()
{
    return doorOpen ? "open" : "closed";
}

void printDivider()
{
    std::println("------------------------------------------------------------");
}

void printStep(int step, const char* title)
{
    std::println("");
    printDivider();
    std::println("Step {}: {}", step, title);
}

void printSnapshot(const ElevatorController& elevator)
{
    std::println(
        "  {:<13} {}",
        "state:",
        stateName(elevator.getState())
    );
    std::println(
        "  {:<13} current={}, target={}",
        "floors:",
        currentFloor,
        targetFloor
    );
    std::println(
        "  {:<13} motor={}, doors={}",
        "hardware:",
        motorName(),
        doorName()
    );
    std::println(
        "  {:<13} physical={}, remote={}, car={}",
        "queues:",
        physicalRequests.size(),
        remoteRequests.size(),
        carCommands.size()
    );
    std::println(
        "  {:<13} {}s",
        "arrival wait:",
        secondsSinceArrival
    );
}

void printExpectation(const char* text)
{
    std::println("  expected: {}", text);
}

void printFailure(const char* text, const ElevatorController& elevator)
{
    std::println("");
    std::println("FAIL: {}", text);
    printSnapshot(elevator);
}

void printBanner()
{
    std::println("");
    std::println("============================================================");
    std::println(" esepp elevator walkthrough");
    std::println("============================================================");
    std::println(" Three floors: 0, 1, 2");
    std::println(" Physical requests are checked before remote requests.");
    std::println(" Each update() call runs one generated state-machine step.");
}

void printSummary(const ElevatorController& elevator)
{
    std::println("");
    std::println("============================================================");
    std::println(" Final state");
    std::println("============================================================");
    std::println(
        " state={} floor={} target={} motor={} doors={} remoteQueue={}",
        stateName(elevator.getState()),
        currentFloor,
        targetFloor,
        motorName(),
        doorName(),
        remoteRequests.size()
    );
}
int main()
{
    printBanner();

    physicalRequests.push_back(2);
    remoteRequests.push_back(1);

    ElevatorController elevator;
    printStep(0, "startup");
    printExpectation("Idle, one physical request queued, one remote request queued");
    printSnapshot(elevator);

    printStep(1, "queue selection");
    printExpectation("physical floor 2 wins over remote floor 1");
    elevator.update();
    printSnapshot(elevator);

    printStep(2, "dispatch toward target");
    printExpectation("target 2 is above current floor 0, so motor starts upward");
    elevator.update();
    printSnapshot(elevator);

    printStep(3, "arrival at floor 2");
    printExpectation("reached target floor, motor stops, doors open");
    currentFloor = 2;
    elevator.update();
    printSnapshot(elevator);

    if (elevator.getState() != ElevatorController::State::Arrived)
    {
        printFailure("expected Arrived after reaching floor 2", elevator);
        return 1;
    }
    if (!doorOpen || motorDirection != 0 || targetFloor != 2)
    {
        printFailure("expected open doors, stopped motor, target floor 2", elevator);
        return 2;
    }

    printStep(4, "car command before timeout");
    printExpectation("car command floor 0 is accepted and doors close on exit");
    carCommands.push_back(0);
    elevator.update();
    printSnapshot(elevator);

    printStep(5, "dispatch downward");
    printExpectation("target 0 is below current floor 2, so motor starts downward");
    elevator.update();
    printSnapshot(elevator);

    printStep(6, "arrival at floor 0");
    printExpectation("reached target floor, motor stops, doors open again");
    currentFloor = 0;
    elevator.update();
    printSnapshot(elevator);

    if (elevator.getState() != ElevatorController::State::Arrived)
    {
        printFailure("expected Arrived after reaching floor 0", elevator);
        return 3;
    }

    printStep(7, "arrival timeout");
    printExpectation("no car command for 10 seconds, so return to Idle");
    secondsSinceArrival = 10;
    elevator.update();
    printSnapshot(elevator);

    if (elevator.getState() != ElevatorController::State::Idle || doorOpen)
    {
        printFailure("expected Idle with doors closed after timeout", elevator);
        return 4;
    }

    printStep(8, "remote request after physical queue drains");
    printExpectation("remote floor 1 is accepted once no physical request remains");
    elevator.update();
    printSnapshot(elevator);

    if (elevator.getState() != ElevatorController::State::DispatchRemote || targetFloor != 1)
    {
        printFailure("expected DispatchRemote with target floor 1", elevator);
        return 5;
    }

    printSummary(elevator);
    std::println("");
    std::println("SUCCESS: generated state machine works.");
    return 0;
}
